### ISSUE TITLE
On its own it is fine but collides with mutation changes

### ISSUE THREAD

**Issue by Demonheim** [chaosvolt/cdda_medieval_mod_reborn#4]
![MMR MC1](https://user-images.githubusercontent.com/42292405/99721735-43163080-2a75-11eb-8bc1-6b0e9fc662bd.png)
![MMR MC2](https://user-images.githubusercontent.com/42292405/99721741-43aec700-2a75-11eb-8ee9-97f13321db5c.png)

**Comment by chaosvolt** [comment]
Arcana neither adds nor edits any items with ID `mutagen_tortoise`. This error indicates that the Mutation Changes mod is out of date, using old syntax for defining how its mutagens work (they used to check for an item flag, now it's wrapped up into the use_action for mutagens).
