### ISSUE TITLE
Possibility of shield having breathability? 

### ISSUE THREAD

**Issue by zakhad** [chaosvolt/cdda_medieval_mod_reborn#7]
Essentially it's causing my character to sweat and thus increase my thirst. It should still have some relative airflow flowing around the shield and around the arm not entirely closed off and i presume give some level of breathability? 

![image](https://user-images.githubusercontent.com/5264667/157204513-2510f223-d687-4da2-b4c8-58e028039de9.png)

**Comment by chaosvolt** [comment]
Ah, let me look into it. Not sure if I can specify it at the item level or if I have to use material hackery to get around that.

EDIT: Material hackery it is, it seems.
